# -*- coding: utf-8 -*-
"""minorproject2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12F2pWEp9gUYNXnoQXAx7xDIQ9gG0kEa8
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


data = {
    "sepal_length": [5.1, 4.9, 6.2, 5.9, 5.5, 6.5, 5.7, 6.3],
    "sepal_width":  [3.5, 3.0, 2.9, 3.0, 2.3, 3.0, 2.8, 3.3],
    "petal_length": [1.4, 1.4, 4.3, 5.1, 4.0, 5.2, 4.1, 6.0],
    "petal_width":  [0.2, 0.2, 1.3, 1.8, 1.3, 2.0, 1.3, 2.5],
    "label": [
        "setosa", "setosa",
        "versicolor", "virginica",
        "versicolor", "virginica",
        "versicolor", "virginica"
    ]
}

df = pd.DataFrame(data)

print("Dataset:\n", df)


X = df.drop("label", axis=1)
y = df["label"]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)


sample = [[5.0, 3.4, 1.5, 0.2]]
prediction = model.predict(sample)

print("Prediction:", prediction[0])

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))